//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public decimal Total { get; set; }
        public string Fecha { get; set; }
    
        public virtual Cliente1 Cliente { get; set; }
    }
}
